### ISSUE TITLE
Multi-GPU/Multi-Node Generations

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#225]
There's currently a bug where attempting to use `generate.py` with horovod or deepspeed will cause them to all overwrite the generations of one another. 

Is there  a way to make them rank-aware and create the filename index from that? so

filename = rank * i

**Comment by lucidrains** [comment]
@afiaka87 hmm, is this with your own custom modified script for generate.py? is it not enough to just generate on one machine?

**Comment by janEbert** [comment]
You need to apply the same principles from `train_dalle.py`:
- Optional: Wrap argument parser and get backend from it.
- Initialize a distributed backend.
- Use the distributed backend API to set up the model (`distrib_backend.distribute`).
- Optional: When analyzing loss, average over all workers with `distrib_backend.average_all(loss)`.
- Properly guard any I/O to the same place so it only happens on the root worker (`if distrib_backend.is_root_worker():`).

To distribute the saving as well, you can do exactly what you said. If all file names are different, there should be no issue. However, keep in mind that for model-partitioned DeepSpeed ZeRO stages, this will fail. I actually haven't yet submitted a PR ([commit 1](https://github.com/janEbert/DALLE-pytorch/commit/6a45836814d101626239626b7edfc9f7a8f1f10a) and [commit 2](https://github.com/janEbert/DALLE-pytorch/commit/845e363988373fadac30d88168efd7e666d42c80)) that handles generations for partitioned models due to possible issues (I can't remember which at the top of my head, sorry).
