### ISSUE TITLE
How can I use Deepspeed Sparse Attention?

### ISSUE THREAD

**Issue by wcshin-git** [lucidrains/DALLE-pytorch#247]
I just installed Deepspeed well.
![image](https://user-images.githubusercontent.com/76698585/117978178-9013f900-b36c-11eb-9bb9-44f6bc22ddf5.png)

And then the next step is same as usual? 
I mean, just change the `--attn_types` arguments
and 
run the command like this?
`python train_dalle.py --vae_path ./vae.pt --image_text_folder /path/to/data --attn_types full,sparse`
Or do I have to run the command line like this?
`deepspeed train_dalle.py [args...] --deepspeed`

**Comment by afiaka87** [comment]
Sorry for the delayed response @wcshin-git 

The sparse attention from deepspeed is (fortunately) provided as a library feature separate from the cli utility. 

As such - you will be using sparse attention correctly in both examples you posted. I recommend the first example as we're still working out some kinks with using the cli command.

`python train_dalle.py --vae_path ./vae.pt --image_text_folder /path/to/data --attn_types full,sparse`

**Comment by afiaka87** [comment]
Congrats on properly installing sparse attention by the way! Did you use the docker container?

**Comment by wcshin-git** [comment]
@afiaka87 I'm installing deepspeed again on another machine, but I got an error...
I just ran `sudo apt-get -y install llvm-9-dev cmake` and then 'DS_BUILD_SPARSE_ATTN=1 pip install deepspeed' 
I reported the error in deepspeed repo [issue](https://github.com/microsoft/DeepSpeed/issues/1079 ).
Do you know why this error occurred? I was installing it the same as last time, but there was an error.

**Comment by afiaka87** [comment]
@wcshin-git most likely your versions are off. Even on the V100 - you will need to be using cuda toolkit 10.1, python 3.7 (can't user later versions), and pytorch 1.6.0. These three requirements are essential to getting it to work. Normally when stuff requires a specific CUDA version I recommend conda - unfortunately conda doesn't help here as it struggles to replace your systems `nvcc` binary.

I assume you're using a rental service or one of the cloud offerings. Do they have the ability to start a machine with a docker container? If so - pytorch's official `pytorch/pytorch-1.6.0-dev` is what you want for the best compatibility.

We also have a docker image in the project files - there are instructions for building it in the README.md, but you will need to have both docker and nvidia-docker installed on the machine in order to build the image.

**Comment by wcshin-git** [comment]
@afiaka87 Thank you for your reply!
I used the dockerfile in this repo and it works now! 
Thank you!
