### ISSUE TITLE
Why in training, the length of transformer token may exceeds the total text + image length?

### ISSUE THREAD

**Issue by cientgu** [lucidrains/DALLE-pytorch#337]
I am a little confused that why the length is not 256 + 1024? Besides, what's the meaning of "remove the last token, since it needs not to be trained" ? https://github.com/lucidrains/DALLE-pytorch/blob/2f1d10e04e537da3e7c9fd6a4057596617823656/dalle_pytorch/dalle_pytorch.py#L548

**Comment by lucidrains** [comment]
@cientgu Hi Shuyang! In normal decoders, one usually has an end-of-string token, so the network indicates when it wants to stop. However, in DALL-E, we are always generating a fixed length (the entire image), so I decided to opt-out of the <eos> token and instead just terminate when it hits the total, fixed sequence length. The last token doesn't need to be trained to predict anything, since it always stops once it hits the last token.

**Comment by cientgu** [comment]
@lucidrains I got it, thanks a lot for this amazing project!
